- name: 'Install nginx on hosts prod-nginx-01 prod-nginx-02'
  hosts: dev
  become: True
  vars:
    nginx_listen_port: 8080
  gather_facts: True

  tasks:
    # - name: Test prod_server
    #   ping:
    - name: 'Install repository'
      yum:
          name: epel-release
          state: present
      tags:
          - epel-package
          - packages

    - name: Install packages nginx
      yum:
          name: nginx
          state: present
      tags:
          - nginx-package
          - packages

    - name: Enable and started nginx_port
      systemd:
          name: nginx
          state: started
          enabled: True
    #
    # - name: Nginx conf files
    #   template:
    #       src: ../templates/ngin.conf.j2
    #       dest: /etc/nginx/nginx.conf
    #       mode: 0600
